ARG VERSION_OPENCODE=latest
ARG VERSION_OPENCLAW=latest

FROM fellow99/playwright-opencode:$VERSION_OPENCODE

ENV HOME=/root

RUN npm config set registry https://registry.npmmirror.com && \
	npm install -g \
	mcporter skills clawhub

RUN npm install -g openclaw@${VERSION_OPENCLAW}  @tobilu/qmd@1.1.6

RUN rm -rf /tmp/* /root/.npm /root/.cache

COPY playwright-opencode-openclaw.pm2.json "${HOME}"

# 暴露端口
EXPOSE 18789 18790 4096 8931 6080

# 设置工作目录为 home
WORKDIR /root/workspace

CMD ["sh", "-c", "pm2-runtime start $HOME/playwright-opencode-openclaw.pm2.json"]
