ARG VERSION_OPENCODE=latest
ARG VERSION_OPENCLAW=latest
ARG JAVA_MAJOR_VERSION=17
ARG PKG_JAVA=openjdk-${JAVA_MAJOR_VERSION}-jdk

FROM fellow99/playwright-opencode-openclaw:$VERSION_OPENCODE-$VERSION_OPENCLAW

ENV HOME=/root

# 设置Java环境变量
ENV JAVA_MAJOR_VERSION=${JAVA_MAJOR_VERSION}
ENV JAVA_HOME=/usr/lib/jvm/java-${JAVA_MAJOR_VERSION}-openjdk-amd64

RUN apt update && \
	apt install -y ${PKG_JAVA} && \
	apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# 设置MAVEN_VERSION和MAVEN_HOME环境变量
ENV MAVEN_VERSION=3.9.12
ENV MAVEN_HOME=/usr/share/maven
# 下载并安装Maven
RUN wget http://apache-mirror.rbc.ru/pub/apache/maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-$MAVEN_VERSION-bin.tar.gz -P /tmp \
    && tar xf /tmp/apache-maven-$MAVEN_VERSION-bin.tar.gz -C /tmp \
    && mv /tmp/apache-maven-$MAVEN_VERSION $MAVEN_HOME \
    && ln -sf $MAVEN_HOME/bin/mvn /usr/bin/mvn
# 配置Maven环境变量
ENV MAVEN_HOME=/usr/share/maven
ENV MAVEN_CONFIG=$HOME/.m2

ENV PATH=$JAVA_HOME/bin;$PATH
